Description of PEVDToyProblem
PEVDToyProblem
PURPOSE
[R,Lambda,Q] = PEVDToyProblem(Num,Disp);
SYNOPSIS
function [R,Lambda,Q] = PEVDToyProblem(ToyIndex,DisplayOn);
DESCRIPTION
[R,Lambda,Q] = PEVDToyProblem(Num,Disp);
  [R,Lambda,Q] = PEVDToyProblem(Num,Disp) implements a number of defined toy
  problems for a parahermitian matrix EVD. The parameter Num determines the
  scenario; for Disp='on', the power spectra of the eigenvalues will be
  displayed.
  PEVDToyProblem(1) returns a 2x2 parahermitian matrix with spectrally
  majorised eigenvalues; all factors are polynomial matrices.
  PEVDToyProblem(2) is a 2x2 example from [Icart & Common, 2013] and [Weiss,
  Pestana, & Proudler, TSP draft] with spectrally majorised eigenvalues. All
  factors are transcendental matrices. The returned approximate eigenvectors
  are NOT normalised, but can serve as a comparison w.r.t. subspace angles
  of an alternative solution.
  PEVDToyProblem(3) is another 2x2 exampled from [Icart & Common, 2013] and
  [Weiss, Pestana, & Proudler, TSP draft] with spectrally unmajorised
  eigenvalues. All factors are polynomial matrices.
  PEVDToyProblem(4) is an `easy' 3x3 parahermitian matrix with spectrally
  unmajorised eigenvalues. There are only pair-wise overlaps that are well-
  separated. All factors are polynomial matrices.
  PEVDToyProblem(5) is a `difficult' 3x3 parahermitian matrix, with
  polynomial matrix factors but algebraic multiplicities up to 3, and some
  closely-spaced intersections.
  Input parameter:
     Num        toy problem number/index
     Disp       displays characteristics (optional for Disp='on')
  Output parameter:
     R          parahermitian matrix
     Lambda     matrix of eigenvalues
     Q          parahermitian matrix
  S. Weiss, UoS, 1/12/2017
CROSS-REFERENCE INFORMATION
This function calls:
ParaHerm H = ParaHerm(G)
PolyMatConv H = PolyMatConv(F,G);
PolyMatDiagSpec P = PolyMatDiagSpec(R,Ndft);
This function is called by:
SOURCE CODE
function [R,Lambda,Q] = PEVDToyProblem(ToyIndex,DisplayOn);
%[R,Lambda,Q] = PEVDToyProblem(Num,Disp);
%
%  [R,Lambda,Q] = PEVDToyProblem(Num,Disp) implements a number of defined toy
%  problems for a parahermitian matrix EVD. The parameter Num determines the
%  scenario; for Disp='on', the power spectra of the eigenvalues will be
%  displayed.
%
%  PEVDToyProblem(1) returns a 2x2 parahermitian matrix with spectrally
%  majorised eigenvalues; all factors are polynomial matrices.
%
%  PEVDToyProblem(2) is a 2x2 example from [Icart & Common, 2013] and [Weiss,
%  Pestana, & Proudler, TSP draft] with spectrally majorised eigenvalues. All
%  factors are transcendental matrices. The returned approximate eigenvectors
%  are NOT normalised, but can serve as a comparison w.r.t. subspace angles
%  of an alternative solution.
%
%  PEVDToyProblem(3) is another 2x2 exampled from [Icart & Common, 2013] and
%  [Weiss, Pestana, & Proudler, TSP draft] with spectrally unmajorised
%  eigenvalues. All factors are polynomial matrices.
%
%  PEVDToyProblem(4) is an `easy' 3x3 parahermitian matrix with spectrally
%  unmajorised eigenvalues. There are only pair-wise overlaps that are well-
%  separated. All factors are polynomial matrices.
%
%  PEVDToyProblem(5) is a `difficult' 3x3 parahermitian matrix, with
%  polynomial matrix factors but algebraic multiplicities up to 3, and some
%  closely-spaced intersections.
%
%  Input parameter:
%     Num        toy problem number/index
%     Disp       displays characteristics (optional for Disp='on')
%
%  Output parameter:
%     R          parahermitian matrix
%     Lambda     matrix of eigenvalues
%     Q          parahermitian matrix
%
%  S. Weiss, UoS, 1/12/2017
switch ToyIndex
  case 1,
    %---------------------------------------------------------------------
    %   2x2 spectrally majorised matrix with polynomial factors
    %---------------------------------------------------------------------
    % one eigenvalue constant, the other highpass
    Lambda = zeros(2,2,3);
    Lambda(:,:,1) = [0 0; 0 -.2];
    Lambda(:,:,2) = [1 0; 0 0.5];
    Lambda(:,:,3) = Lambda(:,:,1)';
    % eigenvectors via an elementary paraunitary operation
    v = [1 -1]'/sqrt(2);
    Q = zeros(2,2,2);
    Q(:,:,1) = eye(2) - v*v';
    Q(:,:,2) = v*v';
    % construction of the `space-time covariance' matrix
    R = PolyMatConv(Q,PolyMatConv(Lambda,ParaHerm(Q)));
  case 2,
    %---------------------------------------------------------------------
    %   2x2 spectrally majorised matrix with transcendental factors
    %---------------------------------------------------------------------
    % problem by Sylvie Icart, also in our TSP16 draft
    R = zeros(2,2,3);
    R(:,:,1) = [0 0; 0 -2];
    R(:,:,2) = [1 1; 1 6];
    R(:,:,3) = R(:,:,1)';
    % determinant etc.
    R11 = [0 1 0]';  R12 = [0 1 0]'; R22 = [-2 6 -2]';
    T = R11+R22;
    S2 = conv(R11-R22,R11-R22) + 4*conv(R12,flipud(conj(R12)));
    % transcendental eigenvalues ... truncated
    N = 20;
    a = ones(N+1,1);
    for n = 0:N,                 % MacLaurin series
       for i = 0:n,
          a(n+1) = a(n+1)*(0.5-i);
       end;
       a(n+1) = a(n+1)/factorial(n+1);
    end;
    a = [1; a];
    xi = -0.355302 + j*0.198559;
    h1 = a.*(xi.^(0:N+1)');
    h2 = a.*(conj(xi).^(0:N+1)');
    h = conv(h1,h2);
    S = 2./abs(xi)*conv(h,flipud(conj(h)));
    L1 = S/2;
    L1(2*(N+1):2*(N+1)+2) = L1(2*(N+1):2*(N+1)+2) + T/2;
    L2 = -S/2;
    L2(2*(N+1):2*(N+1)+2) = L2(2*(N+1):2*(N+1)+2) + T/2;
    Lambda(1,1,:) = L1;
    Lambda(2,2,:) = L2;
    % transcendental eigenvectors ... truncated / approximated
    LL = (length(L1)-1)/2;
    Q = zeros(2,2,2*LL+1);
    % first EV
    Q(1,1,:) = L1;
    dummy = zeros(1,1,3);
    dummy(1,1,:) = R22;
    Q(1,1,LL:LL+2) = Q(1,1,LL:LL+2) - dummy;
    Q(2,1,LL:LL+2) = R12;
    % 2nd EV
    Q(1,2,LL:LL+2) = R12;
    Q(2,2,:) = L2;
    dummy(1,1,:) = R11;
    Q(2,2,LL:LL+2) = Q(2,2,LL:LL+2) - dummy;
    % these would now need normalisation -- divide by the square root :-(
  case 3,
    %---------------------------------------------------------------------
    %   2x2 spectrally unmajorised matrix with polynomial factors
    %---------------------------------------------------------------------
    Q = zeros(2,2,2);
    Q(:,:,1) = [1 1; 0 0]/sqrt(2);
    Q(:,:,2) = [0 0; 1 -1]/sqrt(2);
    Lambda = zeros(2,2,3);
    Lambda(:,:,1) = [1 0; 0 -j];
    Lambda(:,:,2) = [3 0; 0 3];
    Lambda(:,:,3) = Lambda(:,:,1)';
    R = PolyMatConv(Q,PolyMatConv(Lambda,ParaHerm(Q)));
  case 4,
    %---------------------------------------------------------------------
    %   'easy' 3x3 spectrally unmajorised matrix with polynomial factors
    %---------------------------------------------------------------------
    Lambda = zeros(3,3,3);
    Lambda(1,1,:) = [j 4 -j]/4;
    Lambda(2,2,:) = [1/3 3 1/3]/4;
    Lambda(3,3,:) = [j 2 -j]/4;
    Q = zeros(3,3,2);
    v = [1 1 1]'/sqrt(3);
    Q(:,:,1) = eye(3) - v*v';
    Q(:,:,2) = v*v';
    R = PolyMatConv(Q,PolyMatConv(Lambda,ParaHerm(Q)));
  case 5,
    %---------------------------------------------------------------------
    %   'hard' 3x3 spectrally unmajorised matrix with polynomial factors
    %---------------------------------------------------------------------
    Lambda = zeros(3,3,5);
    Lambda(1,1,:) = [1 0 2 0 1]/4;
    Lambda(2,2,:) = [0 -1 2 -1 0]/4;
    Lambda(3,3,:) = [0 -j 4 j 0]/4;
    % eigenvectors via an elementary paraunitary operation
    V = [1 0 -1; 1 1 0; 1 0 1; -1 1 0]'/sqrt(2);
    Q = zeros(3,3,1);
    Q(:,:,1) = eye(3);
    Qi = zeros(3,3,2);
    for i = 1:size(V,2),
      Qi(:,:,1) = eye(3) - V(:,i)*V(:,i)';
      Qi(:,:,2) = V(:,i)*V(:,i)';
      Q = PolyMatConv(Q,Qi);
    end;
    % space-time covariance matrix
    R = PolyMatConv(Q,PolyMatConv(Lambda,ParaHerm(Q)));
  otherwise,
    disp('toy case not implemented');
    R = 1; Lambda = 1; Q = 1;
end;
%-------------------------------------------------------------------------
%  check for display option
%-------------------------------------------------------------------------
if exist('DisplayOn'),
   if strcmp(DisplayOn,'on')==1,
      P = PolyMatDiagSpec(Lambda,1024);
      plot((0:1023)/1024,abs(P));
      xlabel('normalised frequency'); ylabel('magnitude');
   end;
end;