%function SpectralMajorisationDemo();
%SpectralMajorisationDemo()
%
%  This demo demonstrated spectral majorisation achieved by a number of 
%  iterative PEVD algorithms after 50 and 200 iterations for a situation 
%  with known ground truth.
%  The ground truth is provided by a source model generated by the 
%  function GenerateMIMOSources(), which here contains 8 sources with 
%  spectrally majorised PSDs and a paraunitary convolutive mixing matrix
%  of order 16.
%
%  The results reflect approximately those shown in Figures 4 and 5 of [1].
%
%  Reference:
%  
%  [1] 

% S. Weiss, University of Strathclyde, 2/11/2014

M = 8; 
N = 100000;

%-----------------------------------------------------
%  Simulated sources
%-----------------------------------------------------
% set seeds
randn('seed',10); rand('seed',10);
% define source parameters
Angles = [0; 20; 40]/180*pi;        % angles of arrival
Freqs  = [0 0.4 0.5 0.7 0.8 1;      % bandpass definitions
          0 0.35 0.45 0.7 0.8 1;
          0 0.4 0.5 0.8 0.9 1];
% derive array data          
X = zeros(M,N);
for i  = 1:1,
  S = BBSteeringVector(8,Angles(i),25);
  f = firpm(24,Freqs(i,:),[0 0 1 1 0 0]);
  s = filter(f,1,randn(1,N));
  X = X + MIMOFilter(S,s);
end;
% space-time covariance matrix
R = SpaceTimeCovMat(X,55);

%-----------------------------------------------------
%  Polynomial EVD
%-----------------------------------------------------
[H,Gamma] = SMD(R,100,0.0001,0.0001);

%-----------------------------------------------------
%  Polynomial MUSIC
%-----------------------------------------------------
angles = [(-90:5:-40),  (-39:-21),  (-20:5:10), (11:49), (50:5:90)];
Nfft= 512;
[Pss,Ps] = PssMusic(PUPolyMatTrim(H,0.00001),1,Nfft,angles,0.001);
contourf(angles,(1:Nfft),20*log10(Pss))
